import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
import React, { Suspense, useEffect } from "react";
import { Hydrate, useMutation, useQuery } from "react-query";
import Exam from "../components/exam";
import loading from "../components/loading";
// import Exam from "../components/exam";
import Loading from "../components/loading";
import { fetData, putData } from "../modules/api";
import { ExamType } from "../modules/type";
import { queryClient } from "./_app";

const Home: NextPage = () => {
    const { isLoading, data } = useQuery<ExamType>("exam", fetData, {
        refetchOnWindowFocus: false,
        retry: 0,
    });

    const putEmail = useMutation(putData, {
        onSettled: () => {
            console.log("end");
        },
        onSuccess: (data) => {
            queryClient.invalidateQueries("exam");
        },
    });

    if (isLoading) {
        return <Loading />;
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Exam data={data} />
            <button
                onClick={() => {
                    putEmail.mutate();
                }}>
                email 변경
            </button>
        </div>
    );
};

export default Home;
